version: "3"
services:

  app:
    image: defance/coins_ph:latest
    env_file:
        coins.env
    command: bash -c "gunicorn -b 0.0.0.0:8000 --capture-output wsgi"
    volumes:
        - static:/opt/static
    depends_on:
        - db

  nginx:
    image: nginx:alpine
    volumes:
      - static:/opt/static
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - 8000:80

  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=coins_ph

volumes:
  static:
  db:
